env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
os:
- linux
- os
sudo: false
install:
  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev";
    fi
  - bash .ci/travis/install_python.sh $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a
  - conda build -q conda-recipe -c csdms
  - conda install -q bmi-babel --use-local -c csdms
  - pip install coveralls
script:
  - nosetests --with-doctest --with-coverage --cover-package=bmibabel bmibabel
after_success:
- coveralls --verbose
- bash .ci/travis/deploy_to_anaconda.sh bmi-babel
